export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";

export const LOGIN_EXITOSO = "LOGIN_EXITOSO";

export const CERRAR_SESION = "CERRAR_SESION";

export const LISTAR_USUARIOS = "LISTAR_USUARIOS";
export const AGREGAR_USUARIOS = "AGREGAR_USUARIOS";
export const EDITAR_USUARIOS = "EDITAR_USUARIOS";
export const ELIMINAR_USUARIOS = "ELIMINAR_USUARIOS";

export const LISTAR_PRODUCTOS = "LISTAR_PRODUCTOS";
export const AGREGAR_PRODUCTOS = "AGREGAR_PRODUCTOS";
export const EDITAR_PRODUCTOS = "EDITAR_PRODUCTOS";
export const ELIMINAR_PRODUCTOS = "ELIMINAR_PRODUCTOS";

export const LISTAR_CESTA = "LISTAR_CESTA";
export const ELIMINAR_CESTA = "ELIMINAR_CESTA";

export const LISTAR_GALERIAS = "LISTAR_GALERIAS";
export const AGREGAR_GALERIAS = "AGREGAR_GALERIAS";
export const EDITAR_GALERIAS = "EDITAR_GALERIAS";
export const ELIMINAR_GALERIAS = "ELIMINAR_GALERIAS";

export const LISTAR_COMENTARIOS = "LISTAR_COMENTARIOS";
export const AGREGAR_COMENTARIOS = "AGREGAR_COMENTARIOS";
export const ELIMINAR_COMENTARIOS = "ELIMINAR_COMENTARIOS";

export const LISTAR_CONTACTARNOS = "LISTAR_CONTACTARNOS";
export const AGREGAR_CONTACTARNOS = "AGREGAR_CONTACTARNOS";
export const EDITAR_CONTACTARNOS = "EDITAR_CONTACTARNOS";
export const ELIMINAR_CONTACTARNOS = "ELIMINAR_CONTACTARNOS";

export const LISTAR_TERMINOSCONDICIONES = "LISTAR_TERMINOSCONDICIONES";
export const AGREGAR_TERMINOSCONDICIONES = "AGREGAR_TERMINOSCONDICIONES";
export const EDITAR_TERMINOSCONDICIONES = "EDITAR_TERMINOSCONDICIONES";
export const ELIMINAR_TERMINOSCONDICIONES = "ELIMINAR_TERMINOSCONDICIONES";