export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";

export const LOGIN_EXITOSO = "LOGIN_EXITOSO";

export const LISTAR_USUARIOS = "LISTAR_USUARIOS";
export const AGREGAR_USUARIOS = "AGREGAR_USUARIOS";
export const EDITAR_USUARIOS = "EDITAR_USUARIOS";
export const ELIMINAR_USUARIOS = "ELIMINAR_USUARIOS";